### PR TITLE
feat(question): add #09143 - check repeated tuple

### PR DESCRIPTION
**Pull request by jiaowoxiaobala**
Implement type `CheckRepeatedChars<T>` which will return whether type `T`contains duplicated member

### CODE REVIEW

**Comment by jiangshanmeta** [comment]
Hi  @jiaowoxiaobala ,thanks for your contribution.
In order to make a new challenge, you should visit https://github.com/type-challenges/type-challenges/issues
and click the "New Issue" button. 
after that , you will be redirected to https://github.com/type-challenges/type-challenges/issues/new/choose 
find the "New Challenge" and click corresponding button.

**Comment by jiaowoxiaobala** [comment]
Oh，Thanks！！

**Comment by jiaowoxiaobala** [comment]
Oh, Thank you very much！

**Comment by jiaowoxiaobala** [comment]
> Hi @jiaowoxiaobala ,thanks for your contribution. In order to make a new challenge, you should visit https://github.com/type-challenges/type-challenges/issues and click the "New Issue" button. after that , you will be redirected to https://github.com/type-challenges/type-challenges/issues/new/choose find the "New Challenge" and click corresponding button.

Oh, Thanks ！

**Pull request closed without merging**
