### PR TITLE
chore: add korean translations

### PR DESCRIPTION
**Pull request by iwaskorean**
Translated question 9 and 10 into Korean

- 9-deep-readonly
- 10-tuple-to-union

### CODE REVIEW

**Comment by HongxuanG** [comment]
You don't  understand English ?

**Comment by minsgy** [comment]
Thank you for translating!

**Comment by iwaskorean** [comment]
> You don't understand English ?

Is there any problem with my translation?

**Comment by CMERCNFT4ETHMOB** [comment]
> Translated question 9 and 10 into Korean
> 
> - 9-deep-readonly
> - 10-tuple-to-union

> - 13-Aip-variable-cover

**Pull request merged**
