### PR TITLE
enhance: add a new test case to readonly-2

### PR DESCRIPTION
**Pull request by frankie303**
Added a new test case to readonly-2.

While going through some solutions, I found that some people's answers failed when I made this change in the test case so having this additional test can be useful.

### CODE REVIEW

**Comment by antfu** [comment]
I think it was intentional to cover the cases that the function that should handle already exists readonly props.

**Comment by frankie303** [comment]
> I think it was intentional to cover the cases that the function that should handle already exists readonly props.

then, if it makes sense, I can add it as a new test case?

**Comment by antfu** [comment]
Sure, that would be the best

**Comment by frankie303** [comment]
nice! done

**Pull request merged**
