### PR TITLE
feat(extreme):  add currying-2 question

### PR DESCRIPTION
**Pull request by hubvue**
抱歉，时间原因没搞项目脚本就先把题目提交上来了，不知道这个题能不能算的上`extreme`级别的。😂

### CODE REVIEW

**Review by antfu — CHANGES_REQUESTED** [review]
The file name contains a typo which is `zh-CN`. Also please change the challenge number to 430 which reflex to this PR.

It would be great if you can use the issue template doing it next time. Thanks

**Comment by antfu** [comment]
Need some help translating Chinese to English. Leave comments below if anyone gets intersted.

**Comment by hubvue** [comment]
文件命名问题非常抱歉，已经通过issue template提交了题目  #461

**Comment by antfu** [comment]
Thanks. Close in favor of #463

**Pull request closed without merging**
