### PR TITLE
fix: modify README

### PR DESCRIPTION
**Pull request by cutefcc**
modify README for New Challenge DeepMutable: https://github.com/type-challenges/type-challenges/issues/17973

### CODE REVIEW

**Comment by jiangshanmeta** [comment]
As far as I am concerned, the README files are updated automatically by github actions. There must be something wrong with that. weird...

**Comment by cutefcc** [comment]
@jiangshanmeta  I just saw that the README has been updated by antfu, and I think there is no problem with updating it once a day. Since this is my first time contributing to this project, I'm a little confused as to why my code has been merged and it doesn't appear on the show in real time

**Comment by cutefcc** [comment]
@jiangshanmeta  Can I add a translation file for this new topic (17973-medium-deepmutable): eg: README.zh-CN.md? By submitting a PR.
I'm not sure if the READMEs for these different languages are automatically generated. 😂

**Comment by jiangshanmeta** [comment]
@cutefcc  you can directly add README.zh-CN.md . You only need to fill the main content , the header and footer will also be inserted automatically.

This is an example of inserted header:

```html
<!--info-header-start--><h1>DeepMutable <img src="https://img.shields.io/badge/-medium-d9901a" alt="medium"/> <img src="https://img.shields.io/badge/-%23readonly-999" alt="#readonly"/></h1><blockquote><p>by cutefcc <a href="https://github.com/cutefcc" target="_blank">@cutefcc</a></p></blockquote><p><a href="https://tsch.js.org/17973/play" target="_blank"><img src="https://img.shields.io/badge/-Take%20the%20Challenge-3178c6?logo=typescript&logoColor=white" alt="Take the Challenge"/></a> </p><!--info-header-end-->
```

You only need to translate these content into Chinese:

```html
Implement a generic DeepMutable<T> which make every parameter of an object - and its sub-objects recursively - mutable.

You can assume that we are only dealing with Objects in this challenge. Arrays, Functions, Classes and so on do not need to be taken into consideration. However, you can still challenge yourself by covering as many different cases as possible.
```

**Comment by cutefcc** [comment]
@jiangshanmeta  Is it like this?   https://github.com/type-challenges/type-challenges/pull/18041/files

**Comment by jiangshanmeta** [comment]
@cutefcc  Yes. That pr was merged into master , and I trigger the action to generate header and footer for this [file](https://github.com/type-challenges/type-challenges/blob/main/questions/17973-medium-deepmutable/README.zh-CN.md).

And I will close this pr since it's useless.

**Pull request closed without merging**
