### PR TITLE
docs(ja): translate vue-basic-props

### PR DESCRIPTION
**Pull request by Yu0614**
Translated https://github.com/type-challenges/type-challenges/blob/master/questions/213-hard-vue-basic-props/README.md
into Japanese.

Please check sentences out carefully, this is first work of translation for open source of mine !

### CODE REVIEW

**Comment by kawamataryo** [comment]
@Yu0614 

Thanks your PR 😊
But It looks like your translate are still in progress.

Please run this commands in your local repository.

```
$ yarn
$ yarn readme
```

It modifies the batch and links.

**Comment by Yu0614** [comment]
@kawamataryo 

Thanks to reviewing and comments!
As you say, modified with `yarn && yarn readme`. The result is found in https://github.com/type-challenges/type-challenges/pull/306/commits/40d18b56a3302d11204c9027a0bd053d3c4115b4 .

Plz check it out !

**Review by kawamataryo — APPROVED** [review]
LGTM!

**Comment by kawamataryo** [comment]
@Yu0614 

Thanks for your change!!  That is great.

Sorry. I gave you the wrong information...🙇‍♂️
`yarn readme`  commands is not required.
It was set in GitHub Action.
For the next PR, you just need to add the README.

**Pull request merged**
