### PR TITLE
feat(question): add #2640 - PickByPrefix

### PR DESCRIPTION
**Pull request by saxon-y**

### CODE REVIEW

**Comment by antfu** [comment]
Please use the issue template to create new challenges instead. Thanks

**Comment by antfu** [comment]
And btw I think prefixes and suffixes are similar things and we probably only need one of them.

**Comment by saxon-y** [comment]
> And btw I think prefixes and suffixes are similar things and we probably only need one of them.

ok

**Comment by saxon-y** [comment]
@antfu 哥，为什么我提了新题的issue，没生成pr

**Pull request closed without merging**
